### ISSUE TITLE
Issue yo total js (AssertionError)

### ISSUE THREAD

**Issue by shanmmukha1589** [Ealenn/generator-totaljs#1]
shanmmukha1589:~/workspace $ yo totaljs

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Welcome to the terrific │
   `---------´   │    TotalJS generator!    │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? App Name : smm
? Author : 

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/generator-totaljs/generators/app/templates/definitions/
    at EditionInterface.exports._copySingle (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/generator-totaljs/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/generator-totaljs/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at child.writing (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/generator-totaljs/generators/app/index.js:34:15)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/generator-totaljs/node_modules/yeoman-generator/lib/base.js:431:23)
    at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/generator-totaljs/node_modules/run-async/index.js:25:25
    at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/generator-totaljs/node_modules/run-async/index.js:24:19
    at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/generator-totaljs/node_modules/yeoman-generator/lib/base.js:432:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
shanmmukha1589:~/workspace $

**Comment by Ealenn** [comment]
I just added the missing file
Please, update the generator with 
```sh
npm install -g generator-totaljs
```

*Thank you !*
